# Generated by Django 3.1.5 on 2021-01-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0002_faqsscchsl'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageSelector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_no', models.IntegerField(blank=True, null=True)),
                ('lang_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['lang_name', 'lang_no'],
            },
        ),
        migrations.AddField(
            model_name='testname',
            name='lang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mockapp.languageselector'),
        ),
    ]
