# Generated by Django 3.1.5 on 2021-01-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0006_auto_20210113_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcategory',
            options={'ordering': ['category', 'keyword', 'preview_keyword', 'pub_date', 'edit_date']},
        ),
        migrations.AddField(
            model_name='testcategory',
            name='keyword',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='testcategory',
            name='preview_keyword',
            field=models.CharField(default='', max_length=150),
        ),
    ]
