# Generated by Django 3.1.5 on 2021-01-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0008_auto_20210119_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBiharPolice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprehension_show', models.BooleanField(default=False)),
                ('comprehension_doc', models.BooleanField(default=False)),
                ('comprehension', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('question_doc', models.BooleanField(default=False)),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(help_text='Write question')),
                ('opt_doc', models.BooleanField(default=False)),
                ('opt_a', models.TextField(help_text='Option a')),
                ('opt_b', models.TextField(help_text='Option b')),
                ('opt_c', models.TextField(help_text='Option c')),
                ('opt_d', models.TextField(help_text='Option d')),
                ('correct_opt', models.CharField(max_length=1)),
                ('correct_mark', models.FloatField(default=0)),
                ('negative_mark', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.testcategory')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.month')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.subject')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.ssccgltestname')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.year')),
            ],
            options={
                'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'opt_a', 'opt_b', 'opt_c', 'opt_d', 'correct_opt', 'question_number', 'correct_mark', 'negative_mark'],
            },
        ),
        migrations.CreateModel(
            name='BiharPoliceTestName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField(blank=True, null=True)),
                ('test_name', models.CharField(max_length=120)),
                ('keyword', models.CharField(blank=True, max_length=120, null=True)),
                ('is_previous_year_question', models.BooleanField(default=False)),
                ('total_no_of_question', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateField()),
                ('edit_date', models.DateField()),
                ('show_test', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.testcategory')),
                ('language', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='mockapp.languageselector')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.year')),
            ],
            options={
                'ordering': ['test_number', 'year', 'month', 'show_test', 'is_previous_year_question', 'total_no_of_question', 'language', 'test_name', 'pub_date', 'edit_date', 'category'],
            },
        ),
    ]
