# Generated by Django 3.1.5 on 2021-01-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0009_biharpolicetestname_questionbiharpolice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbiharpolice',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.biharpolicetestname'),
        ),
    ]
