# Generated by Django 3.1.5 on 2021-01-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0010_auto_20210119_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbiharpolice',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='questionssccgl',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='questionssccgl',
            name='negative_mark',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='questionsscchsl',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='questionsscchsl',
            name='negative_mark',
            field=models.FloatField(default=0.25),
        ),
    ]
