# Generated by Django 3.1.5 on 2021-01-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0011_auto_20210121_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousyearquestionrrbgroupd',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='previousyearquestionrrbgroupd',
            name='negative_mark',
            field=models.FloatField(default=0.33),
        ),
        migrations.AlterField(
            model_name='previousyearquestionrrbntpc',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='previousyearquestionrrbntpc',
            name='negative_mark',
            field=models.FloatField(default=0.33),
        ),
        migrations.AlterField(
            model_name='questionrrbgroupd',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='questionrrbgroupd',
            name='negative_mark',
            field=models.FloatField(default=0.33),
        ),
        migrations.AlterField(
            model_name='questionrrbntpc',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='questionrrbntpc',
            name='negative_mark',
            field=models.FloatField(default=0.33),
        ),
    ]
