# Generated by Django 3.1.5 on 2021-01-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0013_auto_20210122_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previousyearquestionrrbgroupd',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='previousyearquestionrrbntpc',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='previousyearquestionssccgl',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='previousyearquestionsscchsl',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='previousyearquestionsscjece',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='previousyearquestionsscjeee',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='questionbiharpolice',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='questionrrbgroupd',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='questionrrbntpc',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='questionssccgl',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='questionsscchsl',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='questionsscjece',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AlterModelOptions(
            name='questionsscjeee',
            options={'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'negative_mark']},
        ),
        migrations.AddField(
            model_name='previousyearquestionrrbgroupd',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='previousyearquestionrrbntpc',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='previousyearquestionssccgl',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='previousyearquestionsscchsl',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='previousyearquestionsscjece',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='previousyearquestionsscjeee',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='questionbiharpolice',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='questionrrbgroupd',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='questionrrbntpc',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='questionssccgl',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='questionsscchsl',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='questionsscjece',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AddField(
            model_name='questionsscjeee',
            name='correct_text',
            field=models.TextField(default='', help_text='Correct option value'),
        ),
        migrations.AlterField(
            model_name='previousyearquestionssccgl',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='previousyearquestionsscchsl',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='previousyearquestionsscjece',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='previousyearquestionsscjeee',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='questionssccgl',
            name='negative_mark',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='questionsscjece',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='questionsscjeee',
            name='correct_mark',
            field=models.FloatField(default=1),
        ),
    ]
