# Generated by Django 3.1.5 on 2021-01-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0015_auto_20210123_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbiharpolice',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionbiharpolice', to='mockapp.biharpolicetestname'),
        ),
    ]
