# Generated by Django 3.1.5 on 2021-01-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0016_auto_20210123_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('info_no', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('cat_text', models.CharField(help_text='Write category in text, which is choosen above.', max_length=150)),
                ('image', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.testcategory')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.month')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.year')),
            ],
            options={
                'ordering': ['pub_date', 'title', 'short_description', 'category', 'cat_text', 'month', 'year', 'image', 'info_no'],
            },
        ),
        migrations.CreateModel(
            name='JobInfoPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_no', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('job_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.jobinfo')),
            ],
            options={
                'ordering': ['point_no', 'job_info', 'title', 'description'],
            },
        ),
    ]
