# Generated by Django 3.1.5 on 2021-01-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0017_jobinfo_jobinfopoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfo',
            options={'ordering': ['pub_date', 'title', 'short_description', 'category', 'cat_text', 'month', 'year', 'image', 'info_no', 'keyword']},
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='keyword',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
