# Generated by Django 3.1.5 on 2021-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0018_auto_20210129_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfo',
            options={'ordering': ['pub_date', 'title', 'short_description', 'category', 'cat_text', 'month', 'year', 'image', 'info_no', 'keyword', 'show']},
        ),
        migrations.AlterModelOptions(
            name='jobinfopoints',
            options={'ordering': ['point_no', 'job_info', 'title', 'description', 'show']},
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobinfopoints',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
