# Generated by Django 3.1.5 on 2021-01-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0019_auto_20210129_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfopoints',
            options={'ordering': ['point_no', 'job_info', 'title', 'description', 'show', 'image_show', 'image_url']},
        ),
        migrations.AddField(
            model_name='jobinfopoints',
            name='image_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobinfopoints',
            name='image_url',
            field=models.TextField(blank=True, help_text='Paste image url here.', null=True),
        ),
    ]
