# Generated by Django 3.1.5 on 2021-01-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0020_auto_20210130_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('info_no', models.IntegerField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('cat_text', models.CharField(help_text='Write category in text, which is choosen above.', max_length=150)),
                ('image', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.testcategory')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.month')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.year')),
            ],
            options={
                'ordering': ['pub_date', 'title', 'short_description', 'category', 'cat_text', 'month', 'year', 'image', 'info_no', 'keyword', 'show'],
            },
        ),
        migrations.CreateModel(
            name='ArticleInfoPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_no', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('show', models.BooleanField(default=True)),
                ('image_show', models.BooleanField(default=False)),
                ('image_url', models.TextField(blank=True, help_text='Paste image url here.', null=True)),
                ('job_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.articleinfo')),
            ],
            options={
                'ordering': ['point_no', 'job_info', 'title', 'description', 'show', 'image_show', 'image_url'],
            },
        ),
    ]
