# Generated by Django 3.1.5 on 2021-02-06 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0021_articleinfo_articleinfopoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('pub_date', models.DateField(auto_now=True)),
                ('edit_date', models.DateField(auto_now=True)),
                ('keyword', models.CharField(default='', max_length=150)),
                ('previous_year_keyword', models.CharField(default='', max_length=150)),
                ('preview_keyword', models.CharField(default='', max_length=150)),
                ('preview_previous_year_keyword', models.CharField(default='', max_length=150)),
                ('show', models.BooleanField(default=False)),
                ('preview_show', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'keyword', 'preview_keyword', 'pub_date', 'edit_date', 'previous_year_keyword', 'preview_previous_year_keyword', 'show', 'preview_show'],
            },
        ),
        migrations.AlterField(
            model_name='jobinfo',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.testcategory'),
        ),
    ]
