# Generated by Django 3.1.5 on 2021-03-14 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mockapp', '0026_auto_20210314_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instittuteoperator',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
