# Generated by Django 3.1.5 on 2021-03-14 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mockapp', '0027_auto_20210314_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_inquiry_or_help_phone1', models.CharField(max_length=12)),
                ('for_inquiry_or_help_phone2', models.CharField(max_length=12, null=True)),
                ('for_inquiry_or_help_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('phone1', models.CharField(max_length=12, unique=True)),
                ('phone2', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pin', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('short_text', models.TextField(null=True)),
                ('addresss', models.TextField()),
                ('image', models.TextField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.city')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.instittuteoperator')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.state')),
            ],
            options={
                'ordering': ['added_by', 'name', 'operator', 'city', 'state', 'pin'],
            },
        ),
    ]
