# Generated by Django 3.1.5 on 2021-03-15 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mockapp', '0029_institutetestname'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutetestname',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.city'),
        ),
        migrations.AddField(
            model_name='institutetestname',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mockapp.state'),
        ),
        migrations.CreateModel(
            name='QuestionInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprehension_show', models.BooleanField(default=False)),
                ('comprehension_doc', models.BooleanField(default=False)),
                ('comprehension', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('question_doc', models.BooleanField(default=False)),
                ('question_number', models.IntegerField(blank=True, null=True)),
                ('question', models.TextField(help_text='Write question')),
                ('doc', models.BooleanField(default=False)),
                ('a', models.TextField(help_text='Option a')),
                ('b', models.TextField(help_text='Option b')),
                ('c', models.TextField(help_text='Option c')),
                ('d', models.TextField(help_text='Option d')),
                ('correct_opt', models.CharField(max_length=1)),
                ('correct_text', models.TextField(default='', help_text='Correct option value')),
                ('correct_mark', models.FloatField(default=1)),
                ('negative_mark', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.testcategory')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.month')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.subject')),
                ('test_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionbiharpolice', to='mockapp.institutetestname')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mockapp.year')),
            ],
            options={
                'ordering': ['test_name', 'category', 'subject', 'month', 'year', 'show', 'question', 'a', 'b', 'c', 'd', 'correct_opt', 'question_number', 'correct_mark', 'correct_text', 'correct_text', 'negative_mark'],
            },
        ),
    ]
