# Generated by Django 3.1.5 on 2021-03-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0030_auto_20210315_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
