# Generated by Django 3.1.5 on 2021-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0033_auto_20210315_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='keyword',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
