# Generated by Django 3.1.5 on 2021-03-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0035_questionbysubjecttestname_subjectbytestname'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
